server:
  port: 38003
  servlet:
    context-path: /client-manage
spring:
  redis:
    cluster:
      nodes: 127.0.0.1:20001
    #    password:
    #    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 3000ms
        max-idle: 8
        min-idle: 0
    #   第二个redis数据源
    #  secondaryRedis:
    #    cluster:


security:
  oauth2:
    client:
      client-id: client_id
      client-secret: secret
      user-authorization-uri: http://localhost:8081/auth/oauth/authorize
      access-token-uri: http://localhost:8081/auth/oauth/token
    resource:
      id: manage-client
      user-info-uri: http://localhost:8081/auth/oauth/authorize
#      token-info-uri: http://localhost:8081/auth/token
    authorization:
      check-token-access: http://localhost:8081/auth/oauth/check_token
